-- EXPLAIN SELECT * from ovatadev_test WHERE (NODE_ID = 'adsf') AND (REVISION <= 10) ORDER BY REVISION DESC, REMOVED ASC LIMIT 1
-- EXPLAIN SELECT * FROM ovatadev_test WHERE (PARENT_ID = 'asdf') AND (NAME = 'name') AND (REVISION <= 1000) ORDER BY REVISION DESC, REMOVED ASC
-- EXPLAIN SELECT * FROM ovatadev_test WHERE (PARENT_ID = 'asdf') AND (REVISION <= 1000) ORDER BY NODE_ID ASC, REVISION DESC
EXPLAIN SELECT * from sirene_system_transactions WHERE (REVISION < 1000)

